services:
  portal:
    image: water-content-portal
    build:
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /home/mambauser
    environment:
      - PATH=/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 8000:8000
    volumes:
      - .:/home/mambauser
    entrypoint: ["/bin/bash", "-c"]
    command: ["source ~/.bashrc && mkdocs serve -a 0.0.0.0:8000"]
    profiles: ["portal"]


  portal-shell:
    image: water-content-portal
    build:
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /home/mambauser
    ports:
      - 8000:8000
    volumes:
      - .:/home/mambauser
    profiles: ["shell"]
