name: water-content-portal-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - r-base>=4.3
  - r-tidyverse
  - r-quarto
  - r-patchwork
  - r-terra>= 1.8.5 
  - r-sf
  - r-plotly
  - r-lubridate
  - r-webexercises
  - r-dataretrieval
  - r-whitebox
  - r-tmap
  - r-extremes
  - pip:
      - "mkdocs~=1.6.1"
      - "mkquartodocs~=0.6.0" 
      - "mkdocs-material~=9.6.16"
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-monorepo-plugin
      - mkdocs-minify-plugin
