name: cuahsi-open-learning-env
channels:
  - conda-forge
  - r
dependencies:
  - jupyter
  - python=3.10
  - r-irkernel
  - r-base=4.4.2
  - r-quarto
  - pip
  - pip:
    - jupyter-book==2.0.0b0
    - jupytext #(https://jupytext.readthedocs.io/en/latest/)
    - jupyterlab_myst # required for jupytext to work with MyST markdown files
