site_name: CUAHSI Water Content Portal
repo_name: Water-Content-Portal
repo_url: https://github.com/CUAHSI/Water-Content-Portal
edit_uri_template: 'https://github.com/CUAHSI/Water-Content-Portal'

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - navigation.footer
    - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: default
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - git-revision-date-localized:
      locale: en
      type: datetime
      fallback_to_build_date: true
  - monorepo
  - mkquartodocs:
      force_rebuild: true

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

hooks:
  - scripts/strip_quarto_cell_notation.py

nav:
  - Home: index.md
  - Data Collection Protocols: '!include data-collection-protocols/mkdocs.yml'
  - HydroInformatics Textbook:  
    - Chapter 2: 
      - 'Programming Basics Complete': 'hydroinformatics/2-Programming-Basics/docs/02-Programming_Basics_Demo_COMPLETE.md'

