site_name: CUAHSI Water Content Portal
repo_name: Water-Content-Portal
repo_url: https://github.com/CUAHSI/Water-Content-Portal
edit_uri_template: 'https://github.com/CUAHSI/Water-Content-Portal'

theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - navigation.footer
    - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: default
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - git-revision-date-localized:
      locale: en
      type: datetime
      fallback_to_build_date: true
  - monorepo
  - mkquartodocs:
#     force_rebuild: true
     ignore_pattern: "^.*/hydroinformatics/(6|7|8|9|10|11|12|13|14|15|16|17|18).*"

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

hooks:
  - scripts/strip_quarto_cell_notation.py

nav:
  - Home: index.md
  - Data Collection Protocols: '!include data-collection-protocols/mkdocs.yml'
  - HydroInformatics Textbook:  
    - Chapter 1:
      - 'Intro to Plotting': hydroinformatics/1-Intro-plotting-R/01-Plotting_Demo_COMPLETE.md'  
    - Chapter 2: 
      - 'Programming Basics Blank': 'hydroinformatics/2-Programming-Basics/docs/02-Programming_Basics_Demo_BLANK.md'
      - 'Programming Basics Complete': 'hydroinformatics/2-Programming-Basics/docs/02-Programming_Basics_Demo_COMPLETE.md'
    - Chapter 3:
      - 'Activity Intro Skills': 'hydroinformatics/3-Activity-Intro-Skills/03-Activity-Intro-Skills.md'
    - Chapter 4:
      - 'Intro to Stats': 'hydroinformatics/4-Intro-Stats/04-Intro-Stats-Completed.md'
    - Chapter 5:
      - 'Stats Activity': 'hydroinformatics/5-Intro-Stats-Activity/05-Intro-Stats-Activity.md'

